version: "3.9"
   
services:
  web:
    build: .
    #command: uwsgi --plugins-dir=/usr/lib/uwsgi/plugins --ini uwsgi_settings.ini 
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "81:8000"
    # attach docker sock to interact with the host docker
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:rw