# Generated by Django 4.1.2 on 2023-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_container_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Containers_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
