# Generated by Django 4.1.2 on 2023-01-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_containers_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_id',
            field=models.ManyToManyField(to='main.containers_id'),
        ),
    ]
