# Generated by Django 4.1.2 on 2023-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_container_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers_id',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
