# Generated by Django 4.1.2 on 2023-01-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_containers_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers_id',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
